<a href="https://colab.research.google.com/github/Marcelooyola/Modulo8/blob/main/cl_km_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![logo](https://github.com/cristiandarioortegayubro/BA/blob/main/dba.png?raw=true)

![](https://scikit-learn.org/stable/_static/scikit-learn-logo-small.png)

## **Carga de bibliotecas necesarias**

### **Para el tratamiento de los datos**

In [56]:
import pandas as pd
import numpy as np

In [57]:
import warnings
warnings.filterwarnings("ignore")

### **Para gráficos**

In [58]:
import plotly.express as px
import plotly.graph_objects as go

### **Para preprocesamiento de datos y modelo**

In [59]:
import sklearn
from sklearn import cluster
from sklearn.cluster import KMeans
from sklearn.preprocessing import scale
import sklearn.metrics as metrics
from sklearn.metrics import silhouette_score

## **Extracción de Datos - Creación del DataFrame**

In [60]:
datos = "https://raw.githubusercontent.com/cristiandarioortegayubro/BA/main/Datasets/Clientes.csv"

In [61]:
clientes = pd.read_csv(datos)
clientes

ID  Trabajo  Edad  Salario Compra
0    15624510        1    19    19000     No
1    15810944        1    35    20000     No
2    15668575        0    26    43000     No
3    15603246        0    27    57000     No
4    15804002        1    19    76000     No
..        ...      ...   ...      ...    ...
395  15691863        0    46    41000     Si
396  15706071        1    51    23000     Si
397  15654296        0    50    20000     Si
398  15755018        1    36    33000     No
399  15594041        0    49    36000     Si

[400 rows x 5 columns]

El dataframe contiene 5 variables y 400 observaciones.

Las variables indican:
- **ID:** La identificación del cliente
- **Trabajo:** Corresponde 1 cuando es dependiente y 0 cuando es independiente
- **Edad:** La edad del cliente
- **Salario:** El salario estimado del cliente
- **Compra:** Si, cuando el cliente ha comprado y no cuando no lo ha hecho.

Pero para el desarrollo del algoritmo se simplificara a un problema bidimensional, seleccionando las variables de edad y salario.

## **Eliminando variables**

In [62]:
clientes.info() #visualizacion de los tipos de datos del dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   ID       400 non-null    int64 
 1   Trabajo  400 non-null    int64 
 2   Edad     400 non-null    int64 
 3   Salario  400 non-null    int64 
 4   Compra   400 non-null    object
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [63]:
clientes = clientes.drop(columns=["ID", "Trabajo", "Compra"]) #se elimina la variable no relevante
clientes #vista del dataframe

Edad  Salario
0      19    19000
1      35    20000
2      26    43000
3      27    57000
4      19    76000
..    ...      ...
395    46    41000
396    51    23000
397    50    20000
398    36    33000
399    49    36000

[400 rows x 2 columns]

In [64]:
px.scatter (clientes,
    x = 'Edad',
    y = 'Salario'
)


In [65]:
modelo_km = KMeans(n_clusters= 3, random_state=123)
modelo_km.fit(clientes)

KMeans(n_clusters=3, random_state=123)

In [66]:
modelo_km.predict(clientes)

array([2, 2, 2, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 1, 2,
       0, 2, 0, 2, 1, 0, 2, 2, 0, 2, 0, 0, 2, 0, 2, 1, 2, 0, 0, 1, 0, 0,
       2, 0, 0, 0, 0, 2, 2, 1, 2, 1, 2, 2, 0, 2, 0, 2, 2, 0, 0, 1, 0, 0,
       0, 2, 0, 1, 2, 2, 0, 2, 2, 1, 0, 2, 0, 0, 0, 1, 2, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 2,
       2, 2, 0, 0, 2, 1, 1, 0, 2, 2, 0, 0, 0, 0, 1, 2, 0, 1, 1, 2, 0, 2,
       2, 2, 2, 2, 2, 0, 1, 2, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2,
       0, 2, 2, 0, 1, 0, 1, 2, 1, 1, 1, 2, 0, 1, 2, 0, 2, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 2, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 2, 1, 2, 0, 0, 0, 2, 2, 0, 0, 0, 2, 1, 0,
       0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 1, 2,

In [67]:
modelo_km.labels_

array([2, 2, 2, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 1, 2,
       0, 2, 0, 2, 1, 0, 2, 2, 0, 2, 0, 0, 2, 0, 2, 1, 2, 0, 0, 1, 0, 0,
       2, 0, 0, 0, 0, 2, 2, 1, 2, 1, 2, 2, 0, 2, 0, 2, 2, 0, 0, 1, 0, 0,
       0, 2, 0, 1, 2, 2, 0, 2, 2, 1, 0, 2, 0, 0, 0, 1, 2, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 2, 0, 2,
       2, 2, 0, 0, 2, 1, 1, 0, 2, 2, 0, 0, 0, 0, 1, 2, 0, 1, 1, 2, 0, 2,
       2, 2, 2, 2, 2, 0, 1, 2, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2,
       0, 2, 2, 0, 1, 0, 1, 2, 1, 1, 1, 2, 0, 1, 2, 0, 2, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 2, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 2, 1, 2, 0, 0, 0, 2, 2, 0, 0, 0, 2, 1, 0,
       0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 1, 0, 1, 2,

In [68]:
modelo_km.cluster_centers_

array([[3.55891892e+01, 7.41567568e+04],
       [4.27837838e+01, 1.25310811e+05],
       [3.76737589e+01, 3.47872340e+04]])

In [69]:
fig = go.Figure([go.Scatter(x = clientes.Edad,
                            y = clientes.Salario,
                            mode = "markers",
                            name = "Clusters",
                            marker = dict(color = modelo_km.labels_)),

                 go.Scatter(x = modelo_km.cluster_centers_[:,0],
                            y = modelo_km.cluster_centers_[:,1],
                            mode = "markers",
                            name = "Centroide",
                            marker_color = "orange",
                            marker = dict(size = 12)),
                 ])

fig.update_layout(template =    "gridon",
                  title =       "Edad y Salarios",
                  yaxis_title = "Y",
                  xaxis_title = "X")

fig.show()

In [70]:
modelo_km.inertia_

59489963536.99382

In [71]:
silhouette_score(clientes, modelo_km.labels_ )

0.6021707228326366

## **Número de clusters**

In [72]:
clusters = pd.DataFrame()
inertia = []

In [73]:
clusters["cluster_range"] = range(1, 10)

In [74]:
for k in clusters["cluster_range"]:
    kmeans = KMeans(n_clusters=k, random_state=123).fit(clientes)
    inertia.append(kmeans.inertia_)

In [75]:
clusters["inertia"] = inertia

In [76]:
clusters.inertia = round(clusters.inertia, 4)

In [77]:
clusters.head(10)

cluster_range       inertia
0              1  4.638785e+11
1              2  1.651974e+11
2              3  5.948996e+10
3              4  3.345975e+10
4              5  1.998340e+10
5              6  1.469672e+10
6              7  1.012251e+10
7              8  8.063513e+09
8              9  6.405485e+09

### Graficando clusters óptimos.

In [78]:
fig = px.line(clusters,
              x = "cluster_range",
              y = "inertia",
              markers = True,
              title = "Metodo del codo",
              template = "gridon",
              labels = {"cluster_range":"clusters"})
fig.show()

In [79]:
silhouette = []
k_clusters = range (2,15)


In [80]:
for k in k_clusters:
  kmeans = KMeans(n_clusters=k , random_state=123).fit(clientes)
  silhouette_avg = silhouette_score(clientes, kmeans.labels_)
  silhouette.append(silhouette_avg)


In [81]:
silhouette

[0.5395872953166894,
 0.6021707228326366,
 0.6065989841357814,
 0.6102051324759187,
 0.5852041194017265,
 0.5776987805280969,
 0.5735607821008101,
 0.5696765167572652,
 0.5688965916694889,
 0.5798058454665378,
 0.5873512451306877,
 0.5854988552581679,
 0.5863484685580134]

In [85]:
fig = px.line(x = k_clusters,
              y = silhouette,
              markers = True,
              title = "Metodo de la silueta promedio",
              template = "gridon",
              labels = {"cluster_range":"clusters"})
fig.show()

# **Evaluando el Algoritmo**

## **Algoritmo K-means**

In [ ]:
clientes.head()

Edad  Salario
0    19    19000
1    35    20000
2    26    43000
3    27    57000
4    19    76000

In [ ]:
km = cluster.KMeans(n_clusters = 4, n_init = 20, random_state = 123)
km

KMeans(n_clusters=4, n_init=20, random_state=123)

In [ ]:
km.fit(clientes)

KMeans(n_clusters=4, n_init=20, random_state=123)

In [ ]:
centroids = km.cluster_centers_
labels = km.labels_

In [ ]:
centroids

array([[3.68888889e+01, 5.37407407e+04],
       [4.24788732e+01, 1.26338028e+05],
       [3.59701493e+01, 8.04850746e+04],
       [3.72643678e+01, 2.68735632e+04]])

In [ ]:
centroids = pd.DataFrame(centroids, columns=['Edad', 'Salario'])
centroids

Edad        Salario
0  36.888889   53740.740741
1  42.478873  126338.028169
2  35.970149   80485.074627
3  37.264368   26873.563218

In [ ]:
labels

array([3, 3, 0, 0, 2, 0, 2, 1, 3, 0, 2, 0, 2, 3, 2, 2, 3, 3, 3, 3, 3, 0,
       0, 3, 3, 3, 3, 3, 0, 3, 2, 1, 3, 0, 2, 3, 3, 0, 2, 3, 3, 0, 1, 3,
       2, 3, 2, 0, 1, 2, 3, 0, 2, 3, 0, 0, 0, 2, 3, 1, 3, 2, 0, 1, 2, 0,
       3, 2, 0, 2, 2, 3, 3, 1, 3, 1, 0, 3, 2, 3, 2, 0, 0, 2, 0, 1, 0, 2,
       2, 0, 2, 1, 3, 3, 2, 0, 3, 1, 2, 3, 2, 0, 2, 1, 3, 2, 3, 2, 2, 2,
       2, 2, 0, 0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 3, 3, 2, 0, 3,
       2, 2, 0, 0, 2, 1, 0, 3, 2, 2, 0, 2, 3, 2, 2, 3, 0, 2, 3, 0, 2, 0,
       0, 3, 0, 2, 3, 1, 2, 2, 3, 3, 2, 2, 0, 2, 1, 0, 2, 1, 1, 0, 2, 3,
       0, 3, 3, 3, 3, 2, 1, 0, 0, 0, 2, 0, 2, 3, 2, 3, 0, 2, 2, 0, 2, 3,
       2, 3, 3, 2, 1, 2, 2, 0, 1, 1, 1, 3, 2, 1, 0, 0, 0, 1, 0, 2, 2, 1,
       2, 2, 1, 2, 0, 0, 1, 1, 2, 2, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1, 1, 0,
       2, 1, 2, 1, 0, 1, 0, 2, 3, 0, 1, 1, 0, 2, 2, 0, 2, 1, 2, 1, 1, 2,
       2, 1, 2, 2, 1, 0, 1, 2, 0, 1, 3, 2, 2, 2, 3, 3, 2, 0, 2, 3, 1, 2,
       0, 1, 2, 2, 1, 2, 3, 2, 0, 0, 2, 1, 2, 1, 3,

## **Métricas**

### **Calinski Harabasz**

In [ ]:
metrics.calinski_harabasz_score(clientes, labels)

1698.0186456742101

### **Silhouette**

In [ ]:
metrics.silhouette_score(clientes, labels)

0.6065989841357814

### **Davies Bouldin**

In [ ]:
metrics.davies_bouldin_score(clientes, labels)

0.4605605033920007

In [ ]:
clientes['cluster'] = labels

In [ ]:
clientes

Edad  Salario  cluster
0      19    19000        3
1      35    20000        3
2      26    43000        0
3      27    57000        0
4      19    76000        2
..    ...      ...      ...
395    46    41000        0
396    51    23000        3
397    50    20000        3
398    36    33000        3
399    49    36000        3

[400 rows x 3 columns]

## **Grafico**

### **Plotly**

In [ ]:
fig = go.Figure([go.Scatter(x = clientes.Edad,
                            y = clientes.Salario,
                            mode = "markers",
                            name = "Clusters",
                            marker = dict(color = clientes.Salario,
                                          colorscale = 'bluered',
                                          showscale = False)),

                 go.Scatter(x = centroids.Edad,
                            y = centroids.Salario,
                            mode = "markers",
                            name = "Centroide",
                            marker_color = "orange",
                            marker = dict(size = 12)),
                 ])

fig.update_layout(template =    "gridon",
                  title =       "Edad y Salarios",
                  yaxis_title = "Y",
                  xaxis_title = "X")

fig.show()